# Generated by Django 3.0 on 2019-12-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestopshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestopshop',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='onestopshop',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
