# Generated by Django 3.0 on 2019-12-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestopshop', '0002_auto_20191212_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestopshop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='onestopshop',
            name='quantity',
            field=models.IntegerField(max_length=4),
        ),
    ]
