# Generated by Django 3.0 on 2019-12-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestopshop', '0004_auto_20191212_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestopshop',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
    ]
