# Generated by Django 3.0 on 2019-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestopshop', '0008_auto_20191212_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestopshop',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
