# Generated by Django 3.0 on 2019-12-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebook',
            name='phone',
        ),
    ]
