# Generated by Django 3.0 on 2019-12-03 23:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_remove_phonebook_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
