# Generated by Django 3.0 on 2019-12-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_phonebook_fax_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonebook',
            old_name='fax_number',
            new_name='number',
        ),
    ]
