# Generated by Django 3.0 on 2019-12-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_auto_20191203_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonebook',
            old_name='number',
            new_name='phone_number',
        ),
    ]
