# Generated by Django 3.0 on 2019-12-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_auto_20191203_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
